// // File generated by FlutterFire CLI.
// // ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for android - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for windows - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyBl8z_J0Fyv_fjNrrs7fxDWcZhyuSO_f4g',
//     appId: '1:179654221452:web:b234c08bcf387de13b25a9',
//     messagingSenderId: '179654221452',
//     projectId: 'seesaw1-1486a',
//     authDomain: 'seesaw1-1486a.firebaseapp.com',
//     storageBucket: 'seesaw1-1486a.appspot.com',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyCi_AA_-vpjtB_sgWI0Q58GBYzhzA9x7zU',
//     appId: '1:179654221452:ios:0029ff12cacfd0b33b25a9',
//     messagingSenderId: '179654221452',
//     projectId: 'seesaw1-1486a',
//     storageBucket: 'seesaw1-1486a.appspot.com',
//     iosBundleId: 'com.example.seesaw1',
//   );

//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyCi_AA_-vpjtB_sgWI0Q58GBYzhzA9x7zU',
//     appId: '1:179654221452:ios:f3c5eaa90f948f823b25a9',
//     messagingSenderId: '179654221452',
//     projectId: 'seesaw1-1486a',
//     storageBucket: 'seesaw1-1486a.appspot.com',
//     iosBundleId: 'com.example.seesaw1.RunnerTests',
//   );
// }
